twig:
    file_name_pattern: '*.twig'
    form_themes: ['bootstrap_5_layout.html.twig']

    globals:
        app_version: '%env(APP_VERSION)%'
        app_name: '%env(APP_NAME)%'

when@test:
    twig:
        strict_variables: true
